import { GoogleGenAI, Type } from '@google/genai';
import fs from 'fs';
import path from 'path';

/**
 * Automatically populates NIV scripture verse texts into the generated series content
 * by looking them up in the provided nivData object.
 * 
 * @param {Array} seriesContent - The series content generated by Gemini
 * @param {Object} nivData - The parsed niv.json structure
 * @returns {Array} The series content with verse texts filled in
 */
export function populateBibleVerses(seriesContent, nivData) {
    if (!nivData) return seriesContent;

    return seriesContent.map(entry => {
        if (!entry.body || !Array.isArray(entry.body)) return entry;

        const newBody = entry.body.map(block => {
            // Normalize singular/plural body_type names for robustness
            let bType = block.body_type;
            if (bType === 'scriptures') bType = 'scripture';
            if (bType === 'questions') bType = 'question';
            block.body_type = bType;

            if (block.body_type !== 'scripture' || !block.scriptures || !Array.isArray(block.scriptures)) {
                return block;
            }

            const newScriptures = block.scriptures.map(scripture => {
                const book = scripture.book;
                const chapter = scripture.chapter;
                let verseRange = scripture.verseRange;

                if (!book || !chapter) return scripture;

                // Handle common plural naming convention difference: e.g. "Psalm" vs "Psalms"
                let resolvedBook = book;
                if (book.toLowerCase().trim() === 'psalm') {
                    resolvedBook = 'Psalms';
                }

                // If book still doesn't match directly, try case-insensitive match
                if (!nivData[resolvedBook]) {
                    const matchedKey = Object.keys(nivData).find(
                        k => k.toLowerCase().trim() === resolvedBook.toLowerCase().trim()
                    );
                    if (matchedKey) {
                        resolvedBook = matchedKey;
                    }
                }

                const actualBookData = nivData[resolvedBook];
                const verses = {};

                if (actualBookData && actualBookData[chapter]) {
                    const chapterData = actualBookData[chapter];

                    // Standardize verse range format from model if it contains chapter references like "1:1-19"
                    if (verseRange && String(verseRange).includes(':')) {
                        const parts = String(verseRange).split(':');
                        verseRange = parts[parts.length - 1];
                    }

                    if (verseRange && String(verseRange).trim() !== "") {
                        // Parse ranges: e.g., "1-19", "1-5, 8-12", "1"
                        const parts = String(verseRange).replace(/\s+/g, '').split(',');
                        for (const part of parts) {
                            if (part.includes('-')) {
                                const [start, end] = part.split('-').map(Number);
                                if (!isNaN(start) && !isNaN(end)) {
                                    for (let v = start; v <= end; v++) {
                                        const vStr = String(v);
                                        if (chapterData[vStr]) {
                                            verses[vStr] = chapterData[vStr];
                                        }
                                    }
                                }
                            } else {
                                const vNum = Number(part);
                                if (!isNaN(vNum)) {
                                    const vStr = String(vNum);
                                    if (chapterData[vStr]) {
                                        verses[vStr] = chapterData[vStr];
                                    }
                                }
                            }
                        }
                    } else {
                        // If verseRange is empty or not provided, populate ALL verses in this chapter!
                        for (const [vStr, vText] of Object.entries(chapterData)) {
                            verses[vStr] = vText;
                        }
                    }
                }

                return {
                    book: resolvedBook,
                    chapter: String(chapter),
                    title: scripture.title || "",
                    verses
                };
            });

            return {
                attribution: block.attribution || "Copyright © 1973 1978 1984 2011 by Biblica, Inc. TM\nUsed by permission. All rights reserved worldwide",
                bible_version: block.bible_version || "Scripture quotations taken from The Holy Bible, New International Version® NIV®",
                body_type: "scripture",
                scriptures: newScriptures
            };
        });

        return {
            ...entry,
            body: newBody
        };
    });
}

/**
 * Calls Gemini using structured output to parse the plain text outline
 * and map it to a structured JSON object.
 * 
 * @param {string} outlineText - The raw markdown or plain text outline
 * @param {number|string} startYear - The year to start the dates in (e.g. 2025)
 * @param {string} apiKey - The Gemini API Key
 * @returns {Promise<Object>} The generated series object { bible_series, series_content }
 */
export async function generateSeriesFromOutline(outlineText, startYear, apiKey) {
    if (!apiKey) {
        throw new Error('Gemini API key is required');
    }

    const ai = new GoogleGenAI({ apiKey, httpOptions: { timeout: 120000} });

    const skillPath = path.join(process.cwd(), '.agents', 'skills', 'bible-series-generator', 'SKILL.md');
    let skillContent = '';
    try {
        skillContent = fs.readFileSync(skillPath, 'utf8');
    } catch (error) {
        console.warn('Could not read SKILL.md, please ensure it exists at .agents/skills/bible-series-generator/SKILL.md');
        skillContent = 'You are a structured data extractor specializing in Bible engagement plans for the Waterloo Pentecostal Assembly (WPA) Bible engagement app.\\nYour task is to parse the raw text/markdown outline of a Bible series and convert it into a structured JSON representation matching the schema.';
    }

    const systemPrompt = `You are a structured data extractor specializing in Bible engagement plans for the Waterloo Pentecostal Assembly (WPA) Bible engagement app.
Your task is to parse the raw text/markdown outline of a Bible series and convert it into a structured JSON representation matching the schema.

Here are the strict rules and schema to follow:
${skillContent}`;

    const userPrompt = `Here is the raw outline to convert:
${outlineText}

Start Year: ${startYear}`;

    const response = await ai.models.generateContent({
        model: "gemini-3.5-flash1",
        contents: userPrompt,
        config: {
            systemInstruction: systemPrompt,
            temperature: 0.2,
            safetySettings: [
                { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
                { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
                { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
                { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" }
            ],
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    bible_series: {
                        type: Type.OBJECT,
                        properties: {
                            title: { type: Type.STRING },
                            sub_title: { type: Type.STRING },
                            image_gs_location: { type: Type.STRING },
                            is_active: { type: Type.BOOLEAN },
                            is_visible: { type: Type.BOOLEAN }
                        }
                    },
                    series_content: {
                        type: Type.ARRAY,
                        items: {
                            type: Type.OBJECT,
                            properties: {
                                title: { type: Type.STRING },
                                date: { type: Type.STRING },
                                content_type: {
                                    type: Type.STRING,
                                    enum: ["read", "listen", "reflect", "prayer", "devotional", "draw", "scribe", "memorize"]
                                },
                                body: {
                                    type: Type.ARRAY,
                                    items: {
                                        type: Type.OBJECT,
                                        properties: {
                                            body_type: {
                                                type: Type.STRING,
                                                enum: ["scripture", "text", "question", "link", "image_input"]
                                            },
                                            paragraphs: {
                                                type: Type.ARRAY,
                                                items: { type: Type.STRING }
                                            },
                                            attribution: { type: Type.STRING },
                                            bible_version: { type: Type.STRING },
                                            scriptures: {
                                                type: Type.ARRAY,
                                                items: {
                                                    type: Type.OBJECT,
                                                    properties: {
                                                        book: { type: Type.STRING },
                                                        chapter: { type: Type.STRING },
                                                        title: { type: Type.STRING },
                                                        verseRange: { type: Type.STRING }
                                                    }
                                                }
                                            },
                                            questions: {
                                                type: Type.ARRAY,
                                                items: { type: Type.STRING }
                                            },
                                            text: { type: Type.STRING },
                                            link: { type: Type.STRING }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    });

    const responseText = response.text;
    return JSON.parse(responseText);
}
